export const FETCH_ORGANISATION_REQUEST = 'FETCH_ORGANISATION_REQUEST';
export const FETCH_ORGANISATION_SUCCESS = 'FETCH_ORGANISATION_SUCCESS';
export const FETCH_ORGANISATION_ERROR = 'FETCH_ORGANISATION_ERROR';
export const CREATE_ORGANISATION_REQUEST = 'CREATE_ORGANISATION_REQUEST';
export const CREATE_ORGANISATION_SUCCESS = 'CREATE_ORGANISATION_SUCCESS';
export const CREATE_ORGANISATION_ERROR = 'CREATE_ORGANISATION_ERROR';
