export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ORGANISATION_REQUEST = 'ORGANISATION_REQUEST';
export const ORGANISATION_SUCCESS = 'ORGANISATION_SUCCESS';
export const ORGANISATION_ERROR = 'ORGANISATION_ERROR';
