export const ORGANISATION_REQUEST = 'ORGANISATION_REQUEST';
export const ORGANISATION_SUCCESS = 'ORGANISATION_SUCCESS';
export const ORGANISATION_ERROR = 'ORGANISATION_ERROR';
export const CREATE_ORGANISATION_REQUEST = 'CREATE_ORGANISATION_REQUEST';
export const CREATE_ORGANISATION_SUCCESS = 'CREATE_ORGANISATION_SUCCESS';
export const CREATE_ORGANISATION_ERROR = 'CREATE_ORGANISATION_ERROR';
