export const FETCH_APPLIANCE_CATEGORY_SUCCESS = 'FETCH_APPLIANCE_CATEGORY_SUCCESS';
export const FETCH_APPLIANCE_CATEGORY_ERROR = 'FETCH_APPLIANCE_CATEGORY_ERROR';
export const FETCH_APPLIANCE_CATEGORY_REQUEST = 'FETCH_APPLIANCE_CATEGORY_REQUEST';

export const FETCH_PARAMETERS_SUCCESS = 'FETCH_PARAMETERS_SUCCESS';
export const FETCH_PARAMETERS_ERROR = 'FETCH_PARAMETERS_ERROR';
export const FETCH_PARAMETERS_REQUEST = 'FETCH_PARAMETERS_REQUEST';

export const FETCH_UNITS_SUCCESS = 'FETCH_UNITS_SUCCESS';
export const FETCH_UNITS_ERROR = 'FETCH_UNITS_ERROR';
export const FETCH_UNITS_REQUEST = 'FETCH_UNITS_REQUEST';

export const CREATE_APPLIANCE_CATEGORY_SUCCESS = 'CREATE_APPLIANCE_CATEGORY_SUCCESS';
export const CREATE_APPLIANCE_CATEGORY_ERROR = 'CREATE_APPLIANCE_CATEGORY_ERROR';
export const CREATE_APPLIANCE_CATEGORY_REQUEST = 'CREATE_APPLIANCE_CATEGORY_REQUEST';

export const CREATE_PARAMETERS_SUCCESS = 'CREATE_PARAMETERS_SUCCESS';
export const CREATE_PARAMETERS_ERROR = 'CREATE_PARAMETERS_ERROR';
export const CREATE_PARAMETERS_REQUEST = 'CREATE_PARAMETERS_REQUEST';

export const CREATE_UNITS_SUCCESS = 'CREATE_UNITS_SUCCESS';
export const CREATE_UNITS_ERROR = 'CREATE_UNITS_ERROR';
export const CREATE_UNITS_REQUEST = 'CREATE_UNITS_REQUEST';

export const JUST_CREATED_DATA = 'JUST_CREATED_DATA';
