export const NAVIGATION_CHANGE = 'NAVIGATION_CHANGE';
export const NAVIGATION_RETRIEVED = 'NAVIGATION_RETRIEVED';
export const NAVIGATION_RETRIEVE_REQUEST = 'NAVIGATION_RETRIEVE_REQUEST';
export const SHOW_NAVIGATION_MENU = 'SHOW_NAVIGATION_MENU';
export const HIDE_NAVIGATION_MENU = 'HIDE_NAVIGATION_MENU';

export enum TYPES {
  NAVIGATION_CHANGE,
  NAVIGATION_RETRIEVED,
  NAVIGATION_RETRIEVE_REQUEST,
}
