export const NAVIGATION_CHANGE = 'NAVIGATION_CHANGE';
export const NAVIGATION_RETRIEVED = 'NAVIGATION_RETRIEVED';
export const NAVIGATION_RETRIEVE_REQUEST = 'NAVIGATION_RETRIEVE_REQUEST';

export enum TYPES {
  NAVIGATION_CHANGE,
  NAVIGATION_RETRIEVED,
  NAVIGATION_RETRIEVE_REQUEST,
}
